[workspace]
resolver = "2"
members = [
    "crates/hal-api",
    "crates/core-app",
    "crates/platform-pc-sim",
]

[package]
name = "mcu-hal-sim-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
hal-api = { path = "crates/hal-api" }
core-app = { path = "crates/core-app" }

